version: '3'
services:
  api:
    build: ./api
    container_name: 'api'
    environment:
      FLASK_ENV: development
    depends_on: 
      - db
    env_file:
      - api/.env
    ports:
      - 8000:8000
      - 5678:5678
    links:
      - db:db
    volumes:
      - './api:/app/api'
  db:
    image: "postgres:10.10"
    container_name: 'db'
    ports:
      - '5432:5432/tcp'
    env_file:
      - db/.env
